#!/bin/bash

[ "$1" = "quit"  ] && exit 0
if [ "$1" = "run"  ]; then
  [ -e "${HOME}/.zshenv" ] && mv "${HOME}/.zshenv" "${HOME}/.zshenv.old"
  ln -s $HOME/dotfiles/zsh/.zshenv $HOME/.zshenv
  exit 0
fi

[ -e "${HOME}/dotfiles" ] && mv "${HOME}/dotfiles" "${HOME}/dotfiles.old"
git clone git://github.com/t-cyrill/dotfiles.git $HOME/dotfiles
$HOME/dotfiles/setup run
